// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/AlexAcevedo447/kali-invoice-service/internal/application/command"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/application/query"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/config"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/database"
	http2 "github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/http"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/persistence/postgres"
	"net/http"
)

// Injectors from wire.go:

// Inicializa el router con todas las dependencias ya inyectadas
func InitializeInvoiceAPI() http.Handler {
	pgConfig := config.LoadDatabaseConfig()
	db := database.NewPostgresConnection(pgConfig)
	invoiceCommandRepository := postgres.NewInvoiceCommandRepository(db)
	appCreateInvoiceCommand := command.NewAppCreateInvoiceCommand(invoiceCommandRepository)
	invoiceQueryRepository := postgres.NewInvoiceQueryRepository(db)
	appGetByIdInvoiceQuery := query.NewAppGetByIdInvoiceQuery(invoiceQueryRepository)
	invoiceHandler := http2.NewInvoiceHandler(appCreateInvoiceCommand, appGetByIdInvoiceQuery)
	v := NewRouterHandlers(invoiceHandler)
	handler := http2.NewKaliInvoiceRouter(v...)
	return handler
}
