// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/AlexAcevedo447/kali-invoice-service/internal/application/invoice/command"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/application/invoice/query"
	command2 "github.com/AlexAcevedo447/kali-invoice-service/internal/application/invoiceitem/command"
	query2 "github.com/AlexAcevedo447/kali-invoice-service/internal/application/invoiceitem/query"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/config"
	"github.com/AlexAcevedo447/kali-invoice-service/internal/infrastructure/http/handlers"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

// InitializeApp es el injector principal declarado para wire.
// wire genera wire_gen.go a partir de este archivo.
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := provideDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	invoiceCreator := provideInvoiceCreateRepo(db)
	createInvoiceCommand := command.NewCreateInvoiceCommand(invoiceCreator)
	createInvoiceHandler := handlers.NewCreateInvoiceHandler(createInvoiceCommand)
	invoiceByIDReader := provideInvoiceByIDRepo(db)
	invoiceUpdater := provideInvoiceUpdateRepo(db)
	updateInvoiceCommand := command.NewUpdateInvoiceCommand(invoiceByIDReader, invoiceUpdater)
	updateInvoiceHandler := handlers.NewUpdateInvoiceHandler(updateInvoiceCommand)
	invoiceListReader := provideInvoiceListRepo(db)
	getAllInvoicesQuery := query.NewGetAllInvoicesQuery(invoiceListReader)
	getAllInvoicesHandler := handlers.NewGetAllInvoicesHandler(getAllInvoicesQuery)
	getInvoiceByIDQuery := query.NewGetInvoiceByIDQuery(invoiceByIDReader)
	getInvoiceByIDHandler := handlers.NewGetInvoiceByIDHandler(getInvoiceByIDQuery)
	invoiceStatusUpdater := provideInvoiceStatusRepo(db)
	rabbitMQConfig := provideRabbitMQConfig(cfg)
	invoiceStatusEventPublisher := provideInvoiceStatusEventPublisher(rabbitMQConfig)
	payInvoiceCommand := command.NewPayInvoiceCommand(invoiceStatusUpdater, invoiceStatusEventPublisher)
	payInvoiceHandler := handlers.NewPayInvoiceHandler(payInvoiceCommand, getInvoiceByIDQuery)
	cancelInvoiceCommand := command.NewCancelInvoiceCommand(invoiceStatusUpdater, invoiceStatusEventPublisher)
	cancelInvoiceHandler := handlers.NewCancelInvoiceHandler(cancelInvoiceCommand, getInvoiceByIDQuery)
	invoiceItemCreator := provideInvoiceItemCreateRepo(db)
	createInvoiceItemCommand := command2.NewCreateInvoiceItemCommand(invoiceItemCreator)
	createInvoiceItemHandler := handlers.NewCreateInvoiceItemHandler(createInvoiceItemCommand)
	invoiceItemListReader := provideInvoiceItemListRepo(db)
	getAllInvoiceItemsQuery := query2.NewGetAllInvoiceItemsQuery(invoiceItemListReader)
	getAllInvoiceItemsHandler := handlers.NewGetAllInvoiceItemsHandler(getAllInvoiceItemsQuery)
	invoiceItemByIDReader := provideInvoiceItemByIDRepo(db)
	getInvoiceItemByIDQuery := query2.NewGetInvoiceItemByIDQuery(invoiceItemByIDReader)
	getInvoiceItemByIDHandler := handlers.NewGetInvoiceItemByIDHandler(getInvoiceItemByIDQuery)
	invoiceItemUpdater := provideInvoiceItemUpdateRepo(db)
	updateInvoiceItemCommand := command2.NewUpdateInvoiceItemCommand(invoiceItemByIDReader, invoiceItemUpdater)
	updateInvoiceItemHandler := handlers.NewUpdateInvoiceItemHandler(updateInvoiceItemCommand)
	invoiceItemDeleter := provideInvoiceItemDeleteRepo(db)
	deleteInvoiceItemCommand := command2.NewDeleteInvoiceItemCommand(invoiceItemDeleter)
	deleteInvoiceItemHandler := handlers.NewDeleteInvoiceItemHandler(deleteInvoiceItemCommand)
	idempotencyRepository := provideIdempotencyRepo(db)
	app := provideApp(createInvoiceHandler, updateInvoiceHandler, getAllInvoicesHandler, getInvoiceByIDHandler, payInvoiceHandler, cancelInvoiceHandler, createInvoiceItemHandler, getAllInvoiceItemsHandler, getInvoiceItemByIDHandler, updateInvoiceItemHandler, deleteInvoiceItemHandler, idempotencyRepository)
	return app, nil
}
